travis:
  secure:
    BINSTAR_TOKEN: odtvcd2kXbpuasvcYLDo5xb/+UadMRqoeKg+XSo/3b8VGjsCAGb3CHnNBCKcc8t7/X0/SH8uhvRZJc4cRPwcX81XezGsbqmffLXEeE1NIu7NXxbAFqgUkyXk/TFjbs+6q0g1eHF2+mUW/8xPKOIDU4vDfuLbBLRMW+RCMYWGqCAXy2wI74NIIUS/RgdiRJ0eoe8vP83bYwH0LAqmhPkbZB8XDbuyGc4zUmJhDijgD8Ucn1qZB4e8l77Oy8AqkIIoM3AtX37hUDX1ZpY5+uigvn/vaq5NvCCgV4tipLbIntK2hhUW0S/87yAii3cLEguZ3kGxkogRRdhdTUAmCGLTZ6S5lbT5c9jwKBRaHz8qcfgkCM8XKEFvf7fpM3udcA7sHo5syIeInveGoR1RSZ8O5MSu65NS6AJOiEz7il6S+WQxAhQpciArsNJrv6KSP+BHLUVWPmJbkMfEceNZ3sHhyeCDrFXdgWyRxJbXldgTKvYLOA3yAi/j7RY4cN/T3WY5XhK/uWtATBv7evH46gzKTxYs/YJ+cLKDH0RoMiIK3mlcl5YMDDHEcURA/9NTBIV5xxd65Hci6dVvAX2H9ubUIuteviD9bdQw9pNFXISsDuWCMtzUQR7yj/0T+emOP1UFS12X3D29pK4fufk+PSTZAKw17Fzw4a63zquN+hxNbzg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
